{
 "title": "message_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "send_message_trend_hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(date_format(max(created_at),\"%y-%m-%d %H\")) AS \"time\", count(*) as value FROM message group by DATE_FORMAT(created_at,\"%H\")"
    }
   ]
  },
  {
   "title": "send_msg_trend_minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(date_format(max(created_at),\"%y-%m-%d %H-%i\")) AS \"time\", count(*) as value FROM message group by DATE_FORMAT(created_at,\"%H-%i\")"
    }
   ]
  },
  {
   "title": "send_msg_trend_minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(date_format(max(created_at),\"%y-%m-%d %H-%i\")) AS \"time\", count(*) as value FROM message group by DATE_FORMAT(created_at,\"%H-%i\")"
    }
   ]
  },
  {
   "title": "message",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select date_format(created_at,\"%Y-%m-%d %H:%i:%s\") as send_time,sender_id as sender,receiver_id as receiver, content as content from message order by created_at desc;"
    }
   ]
  }
 ]
}