version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  kafka0:
    image: wurstmeister/kafka
    container_name: kafka_0
    ports:
      - "15000:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://120.26.162.39:15000
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper