# yml 不允许 \t
version:
    "3"
  services:
    redis0:
      image: redis
      container_name: distributed_redis_0
      restart: always
      ports: 
        - 20000:6379
      volumes:
        - $PWD/distributed_conf/redis.conf:/etc/redis/redis.conf
      command: redis-server /etc/redis/redis.conf
    redis1:
      image: redis
      container_name: distributed_redis_1
      restart: always
      ports: 
        - 20001:6379
      volumes:
        - $PWD/distributed_conf/redis.conf:/etc/redis/redis.conf
      command: redis-server /etc/redis/redis.conf
    redis2:
      image: redis
      container_name: distributed_redis_2
      restart: always
      ports: 
        - 20002:6379
      volumes:
        - $PWD/distributed_conf/redis.conf:/etc/redis/redis.conf
      command: redis-server /etc/redis/redis.conf
    redis3:
      image: redis
      container_name: distributed_redis_3
      restart: always
      ports: 
        - 20003:6379
      volumes:
        - $PWD/distributed_conf/redis.conf:/etc/redis/redis.conf
      command: redis-server /etc/redis/redis.conf